### ISSUE TITLE
can't get correct dhash from a icon picture 

### ISSUE THREAD

**Issue by lhtao0607** [benhoyt/dhash#13]
[testpictures.zip](https://github.com/benhoyt/dhash/files/14605702/testpictures.zip)

I attached the picture in the zip file, one is icon type, and the other is png type
dhash of the icon type  returns a value of 0
dhash of the icon type  returns a value of  62738665417926919091179733734494077055

I tried both 1.4 and 1.3 dhash version. Also tried both PIL and wand

do you have any comment about this? Do I need to covert icon picture to png first to get a meaningful value?  Thanks

**Comment by benhoyt** [comment]
Hi there, I can't reproduce this with the latest version of dhash (on the master branch) and the latest version of PIL on Python 3.10.12. I'm using your .png and .ico files in the zip (renamed to shorter filenames), and I get a valid-looking hash for both image types:

```
>>> png = Image.open('favicon.png')
>>> dhash.dhash_int(png)
62655588668192742069404494315346493567
>>> ico = Image.open('favicon.ico')
>>> dhash.dhash_int(ico)
62738665417926919091179733734494077055
```

**Comment by lhtao0607** [comment]
Hi Ben,

Thanks for your quick response.
I just tried the latest version of PIL (10.2.0), and it works now.

I tested on PIL 10.1.0 and Wand, but they failed.
