### ISSUE TITLE
get_num_bits_different() is ambiguous

### ISSUE THREAD

**Issue by MrSnowball-dev** [benhoyt/dhash#14]
The function compares two INT hashes, not any hash the library calculates. I think it is very unintuitive. At least the function have to either convert the inputs to be right, or provide an explanation on what it expects.

**Comment by benhoyt** [comment]
I've clarified the wording [in this commit](https://github.com/benhoyt/dhash/commit/b2271b8c3b7d30fc9abdbcaf5988338a7b6bc76e). The docstring examples also show this, so I think this is all that's needed.
