### ISSUE TITLE
AttributeError: 'module' object has no attribute 'dhash_row_col'

### ISSUE THREAD

**Issue by yasohasakii** [benhoyt/dhash#5]
I run `pip install dhash` in windows 10 OS then I get dhash version 1.3, finally when I run `import dhash` the AttributeError occured. Is any thing wrong?

**Comment by yasohasakii** [comment]
Relized that I fogot there is a script name is "dhash.py" doesn't include dhash_row_col, sorry for botherring.

**Comment by You-Honey** [comment]
What the gentleman is trying to say is that do not your script as "dhash.py" or you will encounter this error.
