### ISSUE TITLE
Optimize dHash

### ISSUE THREAD

**Issue by DarkRedman** [benhoyt/dhash#6]
Hello I use your code since a bit while and I find it pretty awesome and useful, I'm using either to detect copies and also for a project to regenerate a picture as a mozaic of other pictures, first I was using dHash and PIL, then use the basic deltaE with Lab channels to compare overall color difference of two images and went to use OpenCV for lesser and faster comparison. And then I facepalm myself, thinking ...

Maybe it'd be a good idea to do dHash on each Lab channels but I'm not sure how to do it right, the L is the BW equivalent which values goes from 0 to 100 of dHash and a&b are two orthogonal (independant) chroma with a going from -128 to 127 -> green to red and b -128 to 127, thankfully openCV already normalize each value from 0 to 100 after conversion from RGB. 

So I'd like to have your opinion

- Is Luminance is as important as color (or twice) ?
- Should we compute two separate matrix difference, one for luminance and one for colour ?
- What about to port this algorithm to opencv ? (I've started to work on it)

**Comment by benhoyt** [comment]
Hi @DarkRedman, interesting! I actually know extremely little about image processing from a theoretical standpoint -- the dHash algorithm is the first time I had dabbled in this stuff. So unfortunately I can't answer your questions about luminance vs color, etc.

In terms of porting to OpenCV, I think I'd rather leave it as is -- in some ways I think it'd have been better if the dash library was decoupled from image library altogether, and just processed Python arrays. In fact, you can already pass the dhash functions a regular list of "grayscale" values from 0 to 255. So if your values are from 0 to 100 you should be able to just scale/shift them appropriately and pass them right along.
